server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # CoreDNS ????? ?? Kubernetes
        resolver 10.96.0.10 valid=30s ipv6=off;
        set $backend "http://backend-svc:80";
        proxy_pass $backend;
        
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}